[BPK-4172] Upgrade storybook
Skyscanner/backpack pull request #1964
Opened 2020-09-01 15:29 UTC by georgegillams

Remember to include the following changes:
+ [x] `UNRELEASED.yaml`
+ [x] `README.md`
+ [x] Tests
+ [x] Docs (either update [backpack-docs](https://github.com/Skyscanner/backpack-docs) now, or create a follow up ticket)

2020-09-01 16:48 UTC, olliecurtis reviewed
LGTM! Just going to try running it locally and ensure all works as expected

2020-09-03 16:40 UTC, olliecurtis requested changes
Run locally and storybook loads fine with stories, however I noticed the `addons` section is not displaying even though I have it enabled so can't test accessibility, actions and knobs for components

<img width="1678" alt="Screenshot 2020-09-03 at 17 38 56" src="https://user-images.githubusercontent.com/8831547/92142960-82d16280-ee0c-11ea-8a2e-af29a83c257f.png">

2020-09-03 20:08 UTC, georgegillams commented
Good catch! I'll investigate!

2020-09-07 13:05 UTC, georgegillams commented on package.json
>      "@storybook/addon-a11y": "^5.3.14",
For some reason, the latest version get's stuck at "Initialising", and I can't find any related issues. For now I'll leave it here, and we can upgrade separately later.

2020-09-07 14:46 UTC, olliecurtis approved these changes
Tested locally and all seems to be working great!

2020-09-07 15:04 UTC, merged