Enable Next.js compatibility
Skyscanner/backpack pull request #2162
Opened 2021-05-03 14:19 UTC by mbfisher

Remember to include the following changes:

- [ ] `UNRELEASED.md`
- [ ] `README.md`
- [ ] Tests
- [ ] Docs (either update [backpack-docs](https://github.com/Skyscanner/backpack-docs) now, or create a follow up ticket)

2021-05-04 08:52 UTC, mbfisher commented
I've been through the diff to make sure that there's only 3 changes being made:

- Rename JS imports from `.scss` to `.module.scss`
- Rename `.scss` files to `.module.scss`
- Rename `.css` files to `.module.css`

@olliecurtis any clues on the Danger failure? There aren't any licensing headers in the CSS files.

2021-05-04 08:54 UTC, olliecurtis commented
@mbfisher - Will take a look, we recently have been seeing issues with Danger and it might be we are fine to go ahead and ignore it. Will report back soon

2021-05-04 10:00 UTC, mbfisher commented
Good point to cover off, raised by Nick Latham; the [`bpk-stylesheet` public API includes CSS files](https://backpack.github.io/using/base-stylesheet/), and [those file names haven't been change](https://github.com/Skyscanner/backpack/tree/nextjs-compat/packages/bpk-stylesheets)

2021-05-04 10:04 UTC, nicholas-l approved these changes

2021-05-05 10:39 UTC, olliecurtis requested changes
Can you add an UNRELEASED entry?

For this we can probably do:

```
**Added:**
- Backpack compatibility with other build systems. E.g. Next.js
```

2021-05-05 11:25 UTC, olliecurtis approved these changes
LGTM! Thanks so much for this!

![](https://media4.giphy.com/media/rHR8qP1mC5V3G/giphy.gif)

2021-05-06 10:12 UTC, georgegillams approved these changes

2021-05-06 10:13 UTC, merged