[KOA-4540] Update blockquote component to use new spacing grid
Skyscanner/backpack pull request #2281
Opened 2021-10-29 08:59 UTC by anambl

|Before https://backpack.github.io/storybook/?path=/story/bpk-component-blockquote--default-example|After https://backpack.github.io/storybook-prs/2281/?path=/story/bpk-component-blockquote--default-example|
|-|-|
|![image](https://user-images.githubusercontent.com/88667174/139661302-4eeec8ad-46dd-43dd-802a-551b5ac9dfe3.png)|![image](https://user-images.githubusercontent.com/88667174/139661174-930dbde6-a25b-4d6a-b95a-70df0b9fd11f.png)|

Remember to include the following changes:

- [x] `UNRELEASED.md` (See [How to write a good changelog entry](https://github.com/Skyscanner/backpack/blob/main/CHANGELOG_FORMAT.md))
- [ ] `README.md`
- [ ] Tests
- [ ] Docs (either update [backpack-docs](https://github.com/Skyscanner/backpack-docs) now, or create a follow up ticket)

2021-11-08 17:23 UTC, olliecurtis requested changes
Couple of minor improvements for css quality

2021-11-08 17:23 UTC, olliecurtis commented on packages/bpk-mixins/src/mixins/_typography.scss
> +    padding: bpk-spacing-lg() bpk-spacing-lg() bpk-spacing-lg() bpk-spacing-lg();
Same here
```suggestion
    padding: bpk-spacing-lg();
```

2021-11-08 17:27 UTC, anambl commented on packages/bpk-mixins/src/mixins/_typography.scss
> +  padding: bpk-spacing-lg() bpk-spacing-lg() bpk-spacing-lg() bpk-spacing-lg();
Ahh right!

2021-11-09 15:02 UTC, olliecurtis approved these changes

2021-11-12 09:49 UTC, merged