[BD-6170] Backpack price component improvement
Skyscanner/backpack pull request #2483
Opened 2022-06-29 11:37 UTC by colorwin

Remember to include the following changes:

- [x] `UNRELEASED.md` (See [How to write a good changelog entry](https://github.com/Skyscanner/backpack/blob/main/CHANGELOG_FORMAT.md))
- [x] `README.md`
- [x] Tests
- [ ] Docs (either update [backpack-docs](https://github.com/Skyscanner/backpack-docs) now, or create a follow up ticket)

2022-06-30 03:33 UTC, Supremeyh commented on packages/bpk-component-price/README.md
> +    description="a night"
should update `align` in `Props` of `README.md`

2022-06-30 03:33 UTC, Supremeyh commented on packages/bpk-component-price/src/BpkPrice.js
> +import { SIZES, ALIGNS } from './common-types';
`align` is missing in ts `BpkPrice`  type `Props`

2022-06-30 04:38 UTC, jasonhuang-sky requested changes

2022-06-30 04:38 UTC, jasonhuang-sky commented on examples/bpk-component-price/examples.js
> +  LargeLeftLongPriceExample,
Please also add these two more cases
![image](https://user-images.githubusercontent.com/29422130/176592939-6c3c253a-13e1-424d-925d-3387f2bfb021.png)

2022-06-30 04:38 UTC, jasonhuang-sky commented on examples/bpk-component-price/examples.js
> +  <div style={{ width: 170 }}>
Would be better to update to `184` to benefit the design to check it

2022-06-30 04:38 UTC, jasonhuang-sky commented on UNRELEASED.md
> +  - The prop `size` only control font size now
```suggestion
  - The prop `size` only controls font size now
```

2022-06-30 07:38 UTC, jasonhuang-sky approved these changes

2022-07-01 10:22 UTC, olliecurtis requested changes

2022-07-01 10:22 UTC, olliecurtis commented on packages/bpk-component-price/src/BpkPrice.js
> +  const isAlighRight = align === ALIGNS.right;
Minor spelling mistake
```suggestion
  const isAlignRight = align === ALIGNS.right;
```

2022-07-01 10:22 UTC, olliecurtis commented on packages/bpk-component-price/src/BpkPrice.js
> +        isAlighRight && 'bpk-price--right',
```suggestion
        isAlignRight && 'bpk-price--right',
```

2022-07-01 10:22 UTC, olliecurtis commented on packages/bpk-component-price/src/BpkPrice.js
> +        className={isAlighRight && getClassName('bpk-price__columnContainer')}
Fixing spelling and SCSS suggestion made here: 
```suggestion
        className={isAlignRight && getClassName('bpk-price__column-container')}
```

2022-07-01 10:22 UTC, olliecurtis commented on packages/bpk-component-price/src/BpkPrice.js
> +            !isAlighRight && 'bpk-price__spacing',
```suggestion
            !isAlignRight && 'bpk-price__spacing',
```

2022-07-01 10:22 UTC, olliecurtis commented on packages/bpk-component-price/src/BpkPrice.module.scss
> +  &__columnContainer {
Can this be, to follow BEM
```suggestion
  &__column-container {
```

2022-07-01 11:02 UTC, olliecurtis approved these changes

2022-07-01 11:02 UTC, merged