[KOA-5470] Upgrade to Node 16
Skyscanner/backpack pull request #2556
Opened 2022-08-30 12:34 UTC by anambl

Remember to include the following changes:

- [ ] `UNRELEASED.md` (See [How to write a good changelog entry](https://github.com/Skyscanner/backpack/blob/main/CHANGELOG_FORMAT.md))
- [ ] `README.md`
- [ ] Tests
- [ ] Docs (either update [backpack-docs](https://github.com/Skyscanner/backpack-docs) now, or create a follow up ticket)

2022-09-08 15:47 UTC, anambl commented
> > Remove puppeteer dependency
> 
> Won't we need this as part of screenshot testing? This was why originally it was added for compatibility with Storybook Storyshots plugin that we use

I think we don't! We don't use it directly.
`puppeteer` is a peer dependency of `@storybook/addon-storyshots-puppeteer` and with npm versions > 7 it will be installed automatically so we don't need to install it! I removed it as the version we were using was different from the one required by `@storybook/addon-storyshots-puppeteer` 🤔

2022-09-12 14:55 UTC, olliecurtis requested changes

2022-09-12 14:55 UTC, olliecurtis commented on packages/package.json
> +    "react-table": "^7.8.0"
minor nitpick: Can you move this up above `react-transition-group` to keep it alphabetical?

2022-09-13 09:08 UTC, olliecurtis approved these changes

2022-09-13 12:39 UTC, merged