Loom 614 bpk accordion updates
Skyscanner/backpack pull request #2785
Opened 2023-03-17 17:42 UTC by mungodewar

Change description: 
Hi folks 👋 

This is a change to the design of the accordion component to align with the design. I'll be including a screenshot of what has changed below. Namely: 

- Functionality to support the accordion on a dark background
- Divider behaviour change. The divider line between title & content has changed. There will no longer be a divider placed between title and content. This change will make more sense visually 👇  

![Screenshot 2023-03-17 at 16 47 02](https://user-images.githubusercontent.com/89925955/225967430-520c5918-c206-4bdd-b5ae-ec847d8a577f.png)
![Screenshot 2023-03-17 at 16 47 10](https://user-images.githubusercontent.com/89925955/225967436-e86e4a28-fc72-40b2-8c74-57913a1deedd.png)
![Screenshot 2023-03-17 at 16 47 16](https://user-images.githubusercontent.com/89925955/225967437-812f8b50-e8ce-4fda-9dc1-1c1a9a8c8a72.png)

Remember to include the following changes:

- [ ] `README.md` (If you have created a new component)
- [x] Component `README.md`
- [x] Tests
- [x] Storybook examples created/updated

2023-03-20 13:45 UTC, mungodewar commented on packages/bpk-component-accordion/src/BpkAccordionItem.module.scss
> +        @include bpk-border-bottom-sm($bpk-line-night);
Let's ask design about this (the night token usage)
![Screenshot 2023-03-20 at 13 44 48](https://user-images.githubusercontent.com/89925955/226358410-345227a9-f8f6-454e-86b1-a32e45feea1a.png)

2023-03-21 13:03 UTC, mungodewar commented on packages/bpk-component-accordion/src/BpkAccordionItem.module.scss
> +        @include bpk-border-bottom-sm($bpk-line-night);
Updated the colours.

2023-03-21 15:21 UTC, olliecurtis requested changes
A small minor thing, but otherwise all looks great!

2023-03-22 10:52 UTC, olliecurtis approved these changes
LGTM!

![Thank you gif](https://media.giphy.com/media/ZfK4cXKJTTay1Ava29/giphy.gif)

2023-03-22 10:52 UTC, merged