feat: change map marker default color
Skyscanner/backpack pull request #3028
Opened 2023-10-07 06:38 UTC by LuoTuxiu

The style of Component `BpkIconMarker` changed

| Before                        | After                         |
| ----------------------------- | ----------------------------- |
| <img width="321" alt="image" src="https://github.com/Skyscanner/backpack/assets/12047146/5fcc56d1-74d2-4733-aa11-97765c3aa46b"> | <img width="383" alt="image" src="https://github.com/Skyscanner/backpack/assets/12047146/6e0a0de0-8549-41b2-9c9f-c677f1a7a97b"> |

## Figma

https://www.figma.com/file/kOzCI1zFdIOcZGkZr2vHTR/Map-Redesign--(Google-Map%2C-Pins%2C-POI)?type=design&node-id=488-14862&mode=design&t=q14DEHsRfsxPVLRK-0

Remember to include the following changes:

- [ ] `README.md` (If you have created a new component)
- [ ] Component `README.md`
- [ ] Tests
- [ ] Storybook examples created/updated
- [ ] For breaking changes or deprecating components/properties, migration guides added to the description of the PR. If the guide has large changes, consider creating a new Markdown page inside the component's docs folder and link it here

2023-10-08 05:11 UTC, jasonhuang-sky commented on packages/bpk-component-map/src/BpkIconMarkerBackground.module.scss
> +    $bpk-marcomms-purple
It's likely a deprecated color token, are you sure it's correct?

2023-10-08 05:11 UTC, jasonhuang-sky commented on packages/bpk-component-map/src/BpkIconMarkerBackground.module.scss
> +    fill: $bpk-marcomms-dark-sky;
same this one

2023-10-08 05:11 UTC, jasonhuang-sky commented on packages/bpk-component-map/src/BpkIconMarkerBackground.module.scss
> +      $bpk-marcomms-dark-sky
same this one

2023-10-08 10:20 UTC, jasonhuang-sky approved these changes

2023-10-09 08:45 UTC, olliecurtis requested changes
I notice that the disabled version of the icon marker is still marked as green. Could you check if this is expected or not?

https://github.com/Skyscanner/backpack/pull/3028/files#diff-910dcd001032877120cf36bfb367b3b519423a2e451cee375701ed560386ed3cR82

![Screenshot 2023-10-09 at 09 43 45](https://github.com/Skyscanner/backpack/assets/8831547/0fc16f1f-1740-4707-983f-09446a42431a)

2023-10-09 08:53 UTC, LuoTuxiu commented
> I notice that the disabled version of the icon marker is still marked as green. Could you check if this is expected or not?
> 
> https://github.com/Skyscanner/backpack/pull/3028/files#diff-910dcd001032877120cf36bfb367b3b519423a2e451cee375701ed560386ed3cR82
> 
> ![Screenshot 2023-10-09 at 09 43 45](https://user-images.githubusercontent.com/8831547/273534880-0fc16f1f-1740-4707-983f-09446a42431a.png)

Thanks. @olliecurtis i think we just focus on changing the color which is default and selected. And we have **not use disabled status**  at our repo for now. So maybe i should confirm with our disigner?

2023-10-09 09:00 UTC, anambl commented
> > I notice that the disabled version of the icon marker is still marked as green. Could you check if this is expected or not?
> > https://github.com/Skyscanner/backpack/pull/3028/files#diff-910dcd001032877120cf36bfb367b3b519423a2e451cee375701ed560386ed3cR82
> > ![Screenshot 2023-10-09 at 09 43 45](https://user-images.githubusercontent.com/8831547/273534880-0fc16f1f-1740-4707-983f-09446a42431a.png)
> 
> Thanks. @olliecurtis i think we just focus on changing the color which is default and selected. And we have **not use disabled status** at our repo for now. So maybe i should confirm with our disigner?

I think we should be updating the disabled status one as well as this is changing the main icon marker component and is traveller facing so keeping both colours will be confusing and inconsistent.

2023-10-09 09:00 UTC, anambl commented
@LuoTuxiu just checking - is this change meant to be stable or will there be an experiment running to test it?

2023-10-12 09:09 UTC, LuoTuxiu commented
> @LuoTuxiu just checking - is this change meant to be stable or will there be an experiment running to test it?

@olliecurtis  i confrim with our PO, this will release directly.

2023-10-16 15:54 UTC, olliecurtis requested changes

2023-10-16 15:54 UTC, olliecurtis commented on examples/bpk-component-map/examples.js
> +// import ParkingIconSm from '../../packages/bpk-component-icon/sm/parking';
Can this be removed?

2023-10-16 15:54 UTC, olliecurtis commented on examples/bpk-component-map/examples.js
> +// const AlignedParkingIconSm = withRtlSupport(ParkingIconSm);
Same here

2023-10-16 15:54 UTC, olliecurtis commented on examples/bpk-component-map/examples.js
> +    // disabled: false,
Same here

2023-10-16 15:54 UTC, olliecurtis commented on examples/bpk-component-map/examples.js
> +    // disabled: false,
Same here

2023-10-16 15:54 UTC, olliecurtis commented on examples/bpk-component-map/examples.js
> +    // disabled: false,
Same here

2023-10-16 15:54 UTC, olliecurtis commented on examples/bpk-component-map/examples.js
> +    // disabled: false,
Same here

2023-10-16 15:54 UTC, olliecurtis commented on examples/bpk-component-map/examples.js
> +  // },
Can this be removed?

2023-10-16 15:54 UTC, olliecurtis commented on examples/bpk-component-map/examples.js
> +            // disabled={venue.disabled}
Can this be removed?

2023-10-16 15:54 UTC, olliecurtis commented on packages/bpk-component-map/src/BpkIconMarker-test.js
> +  // });
Can this be removed?

2023-10-16 15:54 UTC, olliecurtis commented on packages/bpk-component-map/src/BpkIconMarker.js
> +  // disabled: boolean,
Same here

2023-10-16 15:54 UTC, olliecurtis commented on packages/bpk-component-map/src/BpkIconMarker.js
> +    // disabled,
Same here

2023-10-16 15:54 UTC, olliecurtis commented on packages/bpk-component-map/src/BpkIconMarker.js
> +      // && !disabled
Can you remove this?

2023-10-16 15:54 UTC, olliecurtis commented on packages/bpk-component-map/src/BpkIconMarker.js
> +    // disabled && 'bpk-icon-marker__icon--disabled',
Same here

2023-10-16 15:54 UTC, olliecurtis commented on packages/bpk-component-map/src/BpkIconMarker.js
> +        // disabled={disabled}
Can you remove this?

2023-10-16 15:54 UTC, olliecurtis commented on packages/bpk-component-map/src/BpkIconMarker.js
> +          // disabled={disabled}
Can you remove this?

2023-10-16 15:54 UTC, olliecurtis commented on packages/bpk-component-map/src/BpkIconMarker.js
> +            // && !disabled
Can you remove this?

2023-10-16 15:54 UTC, olliecurtis commented on packages/bpk-component-map/src/BpkIconMarker.js
> +  // disabled: PropTypes.bool,
Can you remove this?

2023-10-16 15:54 UTC, olliecurtis commented on packages/bpk-component-map/src/BpkIconMarker.js
> +  // disabled: false,
Can you remove this?

2023-10-16 15:54 UTC, olliecurtis commented on packages/bpk-component-map/src/BpkIconMarker.module.scss
> +    // }
Can you remove this?

2023-10-17 12:15 UTC, LuoTuxiu commented
Hi， @olliecurtis  i have updated all deleted annotation, could you help to reivew? Thanks

2023-10-17 15:08 UTC, olliecurtis approved these changes

2023-10-17 15:10 UTC, merged